[PATCH] 2.5.23 i2c updates 4/4
i2c-elektor.c:Adding call to pcf_isa_init to i2c_pcfisa_init causes:
i2c-elektor.o: In function `i2c_pcfisa_init':
i2c-elektor.o(.text.init+0x95): undefined reference to `local symbol
i2c-elektor.c: fix by removing __exit for inline compiling.