[IA64] ia64 audit build fix
With CONFIG_AUDITSYSCALL=n:

arch/ia64/kernel/ptrace.c: In function `syscall_trace_enter':
arch/ia64/kernel/ptrace.c:1615: warning: implicit declaration of function `audit_syscall_entry'
arch/ia64/kernel/ptrace.c: In function `syscall_trace_leave':
arch/ia64/kernel/ptrace.c:1631: warning: implicit declaration of function `audit_syscall_exit'

And the link fails, due to audit_syscall_entry() not being present.

Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Tony Luck <tony.luck@intel.com>