[PATCH] drivers/net/wan/cycx_x25.c:189: warning: conflicting types for built-in function 'log2'
From: Jesper Juhl <juhl-lkml@dif.dk>

To silence the warning in $subject, rename log2 to cycx_log2 in this file
to remove the clash, so there's no doubt that this file uses it's own
defined log2 function.

Signed-off-by: Jesper Juhl <juhl-lkml@dif.dk>
Signed-off-by: Andrew Morton <akpm@osdl.org>