[PATCH] i386/io_apic init section fixups
Code section errors in i386/io_apic.c found by scripts/reference_init.pl.
Looks like they could cause problems for a few drivers or in a real hotplug
environment.

Error: ./arch/i386/kernel/io_apic.o .text refers to 000018ff R_386_PC32        .init.text

call chain:
  snd_mpu401_acpi_resource
    acpi_register_gsi
      mp_register_gsi
	io_apic_set_pci_routing
{A}	  ioapic_register_intr
	    IO_APIC_irq_trigger
	      find_irq_entry

Error: ./arch/i386/kernel/io_apic.o .text refers to 00001967 R_386_PC32        .init.text

	(as above thru {A}, then:)
	  IO_APIC_irq_trigger
	    irq_trigger
	      MPBIOS_trigger	>> removing __init from this led to
				   needing to remove __init from
				   EISA_ELCR also.

Signed-off-by: Randy Dunlap <rddunlap@osdl.org>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>